services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seller_tray_app
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    depends_on:
      - mysql
    ports:
      - "5173:5173"
    mem_limit: 2g

  nginx:
    image: nginx:alpine
    container_name: seller_tray_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: seller_tray_mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seller-tray
      MYSQL_USER: seller-tray
      MYSQL_PASSWORD: seller-tray
    ports:
      - '3337:3306'
    expose:
      - 3306
    networks:
      - laravel_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: seller_tray_elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
      - ELASTIC_USERNAME=elastic
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
      - "9300:9300"
    expose:
      - 9200
    networks:
      - laravel_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: seller_tray_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://seller_tray_elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
    ports:
      - "5601:5601"
    networks:
      - laravel_network
    depends_on:
      - elasticsearch

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
  elasticsearch_data:
